language: python
services:
  - docker
install:
  - make deps
script:
  - make test_cov
  - make lint
  - make docker_build
after_success:
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: warm-wave-53453
  api_key: ${HEROKU_API_KEY}
